### ISSUE TITLE
about dataset preprocessing

### ISSUE THREAD

**Issue by amiltonwong** [Sentient07/IFMatch#2]
Hi, @Sentient07 ,

From the section [Dataset and Pre-Processing](https://github.com/Sentient07/IFMatch#dataset-and-pre-processing), could you elaborate it further? e.g. it's better to illustrate an example on specific dataset, such as FAUST.

Thanks~

**Comment by Sentient07** [comment]
Sure, we provide the test shapes here: https://nuage.lix.polytechnique.fr/index.php/s/gb8D3KHBeb7zqNL . I've updated the README. Feel free to reopen if there is something unclear, closing for now.
