### ISSUE TITLE
Evaluation setting--template info.

### ISSUE THREAD

**Issue by chunjins** [Sentient07/IFMatch#3]
Hi there,

Your work is excellent. I like it very much.

Now I am trying to run the evaluation code with the pre-trained model and the test-set shapes (FAUST-Remesh dataset) you provided. But it seems that I need the template shape, I think it should be the one you use for training, right? Could you provide it?

I randomly set the template shape as 'tr_reg_080', but it does not work, since the corresponding surface point file does not have 'trig_id' and 'bary_coord'.

`  File "/IFMatch/code/dataset.py", line 220, in _get_template_info
    templ_trig_id = np.squeeze(templ_surf_mat['trig_id'])
KeyError: 'trig_id'`

**Comment by Sentient07** [comment]
Hello,

Thanks for your interest. I've added the templates to our data directory (https://nuage.lix.polytechnique.fr/index.php/s/RjtprA8gSjgnEkt?path=%2F). We use the normal template at training and the high-res (called dense) for evaluation. Feel free to reopen if you still have questions.

**Comment by chunjins** [comment]
Thanks for providing the template file.

Now I meet another problem. According to the paper,  there is only one human template for all different datasets, right? Then, how do you get the ground truth correspondences between the template and all training shapes?

I think it is related to the parameters of 'trig_id' and 'bary_coord'?  But how can I get them?
