### ISSUE TITLE
Template shape setting

### ISSUE THREAD

**Issue by chunjins** [Sentient07/IFMatch#4]
Thanks for providing the template file.

Now I meet another problem. According to the paper, there is only one human template for all different human datasets and one animal template for animal datasets, right? Then, how do you get the ground truth correspondences between the template and all training shapes? Are there any pre-processing code?

I think it is related to the parameters of 'trig_id' and 'bary_coord'? But how can I get them?

**Comment by Sentient07** [comment]
It's because our template is from FAUST and training shapes are from SURREAL, both are derived from SMPL. So they share same vertex ordering and connectivity. Thus, barycentric coordinates must be (approx) same.
